language: python

python:
  - "3.6"
  - "3.7"

install:
  - npm install -g quicktype
  - pip3 install -r docs/requirements.txt
  - pip3 install -r requirements.txt
  
script:
  - make docs
  - make code

after_success:
  - pip3 install .

deploy:
  provider: pypi
  user: __token__
  password: $PYPI_TRAVIS_TOKEN # Set in the settings page of your repository, as a secure variable
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    branch: staging

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master